[package]
name = "aw_custom_response"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0"
serde = {version = "1.0",features=["derive"]}
actix-web = "4"
sqlx = { version = "0.7", features = ["mysql", "runtime-tokio-rustls", "macros"] }
futures = "0.3.31"
